# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 70)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 10, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.LBL_IP = QtWidgets.QLabel(Dialog)
        self.LBL_IP.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.LBL_IP.setObjectName("LBL_IP")
        self.LBL_name = QtWidgets.QLabel(Dialog)
        self.LBL_name.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.LBL_name.setObjectName("LBL_name")
        self.LE_IP = QtWidgets.QLineEdit(Dialog)
        self.LE_IP.setGeometry(QtCore.QRect(80, 10, 221, 20))
        self.LE_IP.setObjectName("LE_IP")
        self.LE_name = QtWidgets.QLineEdit(Dialog)
        self.LE_name.setGeometry(QtCore.QRect(80, 40, 221, 20))
        self.LE_name.setObjectName("LE_name")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Server"))
        self.LBL_IP.setText(_translate("Dialog", "IP and PORT"))
        self.LBL_name.setText(_translate("Dialog", "Name"))
